name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    runs-on: ubuntu-latest
    
    env:
      GOOS: js
      GOARCH: wasm
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Setup PATH for wasm
      run: echo "${{env.GOROOT}}/misc/wasm" >> $GITHUB_PATH

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 14

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
