name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    runs-on: ubuntu-latest
    
    env:
      GOOS: js
      GOARCH: wasm
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 12
    
    - id: read-wasm-exec-path
      name: Read wasm-exec path
      run: echo "::set-output name=wasm-exec-path::$(go env GOROOT)/misc/wasm"

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        PATH: ${{env.PATH}}:${{steps.read-wasm-exec-path.outputs.wasm-exec-path}}
      run: go test -v ./...
